services:
  bfn_mysql:
    image: mysql:8.0
    container_name: bfn_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1324321 #Change this to ur password
      MYSQL_DATABASE: bfn_db
      MYSQL_USER: bfn_user
      MYSQL_PASSWORD: bfn_password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  bfn_django:
    build: .
    container_name: bfn_django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      bfn_mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=bfn_mysql
      - DJANGO_DB_PORT=3306