# Generated by Django 5.2.11 on 2026-04-30 13:09

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('marketplace', 'Category')

    categories = [
        "Bakery",
        "Dairy",
        "Fruit & Vegetables",
        "Meat",
        "Seafood",
        "Drinks",
        "Snacks",
        "Prepared Meals",
        "Vegan",
        "Gluten Free",
    ]

    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_suborder_status'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]

