# Generated by Django 6.0.4 on 2026-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('out_of_season', 'Out of Season'), ('unavailable', 'Unavailable')], max_length=20),
        ),
    ]
