# Generated by Django 5.2.11 on 2026-03-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
        ('marketplace', '0004_order_suborder_orderitem'),
    ]

    operations = [
    ]
