# Generated by Django 5.2.11 on 2026-05-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_status'),
        ('marketplace', '0006_order_special_instructions'),
    ]

    operations = [
    ]
