# Generated by Django 6.0.4 on 2026-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_review_unique_together_product_surplus_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('out_of_season', 'Out of Season'), ('all_year', 'All Year'), ('unavailable', 'Unavailable')], max_length=20),
        ),
    ]
