# Generated by Django 5.2.11 on 2026-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_suborder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
