# Generated by Django 6.0.5 on 2026-05-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
