# Generated by Django 6.0.5 on 2026-05-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_product_status'),
        ('marketplace', '0011_alter_order_stripe_session_id'),
    ]

    operations = [
    ]
