# Generated by Django 6.0.5 on 2026-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_merge_20260507_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
