# Generated by Django 5.2.11 on 2026-04-30 13:00

from django.db import migrations

def create_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = "admin_account"
    email = "admin@bristolfoodnetwork.co.uk"
    password = "admin123"

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username='admin_account',
            email='admin@example.com',
            password='admin123'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]