# Generated by Django 5.2.11 on 2026-04-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('organisation', 'Organisation')], default='organisation', max_length=20),
        ),
    ]
